### ISSUE TITLE
Unable to signup - Privacy policy checkbox.

### ISSUE THREAD

**Issue by veeeringoff** [aicodingtu/pond-alpha#2]
![image](https://github.com/aicodingtu/pond-alpha/assets/42495759/a0d428dc-a353-4ad0-a70b-9f9eb08d0a57)

Unable to signup although I have the PP/TC checkbox checked. Tried it on both : 
- Chome Version 114.0.5735.198 (Official Build) (64-bit)
- Mozilla Firefox : 114.0.2 (64-bit)

Can anyone else please verify this as well please?

**Comment by aicodingtu** [comment]
Thanks for the issue - we have deployed a fix just now and tried it on our side. Please try again 🚀 ! Feel free to reopen the issue if it doesn't work for you
