### ISSUE TITLE
Quacks don't seem to get saved.

### ISSUE THREAD

**Issue by veeeringoff** [aicodingtu/pond-alpha#3]
So I add in a quack by highlighting a section of the paper. It gets added to the left section as seen in the screenshot(top quack added by me)

![image](https://github.com/aicodingtu/pond-alpha/assets/42495759/fcb693b5-4a71-4af7-8dd5-5fd8e4f1f2ab)

I come back to the paper, I don't see any of the quacks I added.
Does not work for section highlight, text highlight either.

Also is there a way to see all the quacks I've added? 

Thanks.

**Comment by aicodingtu** [comment]
Yes absolutely! This was a bug from making all the documents and quacks public. We fixed it by auto-adding the document to your library if you highlight from another users' document.  

If you have any other problems, feel free to open another issue 🚀
