### ISSUE TITLE
UX Issues and suggesstions

### ISSUE THREAD

**Issue by veeeringoff** [aicodingtu/pond-alpha#4]
The UI looks minimal and clean but I have found some issues with the UX.

Opening a paper :
1. Currently the only way to open a paper is by clicking the button under the quack. It would be better if one could open the paper with the click of the paper title instead of the "Copy DOI" action that it currently performs.

![paper_opening](https://github.com/aicodingtu/pond-alpha/assets/42495759/2d98f5ea-dd78-4a08-ae54-57e0d4cfcb0e)

2. The link in the header does not seem to work. I expect this to take me to the home page.
![home_link](https://github.com/aicodingtu/pond-alpha/assets/42495759/8c9d4f56-82e7-4b9d-a96d-a3362a9def61)

**Comment by aicodingtu** [comment]
Thanks! Your second suggestion is live now 🚀 . For your first, we are working on some design thoughts on DOI, more to come!

**Comment by aicodingtu** [comment]
We added a copy icon and took your suggestion ! 🚀
