### ISSUE TITLE
Unable to edit/delete highlights.

### ISSUE THREAD

**Issue by limsanky** [aicodingtu/pond-alpha#5]
Hello!

Highlights are not editable for me. I think it would be great if this function is implemented (if it already has been implemented, I am unable to find it).

Thanks!

**Comment by aicodingtu** [comment]
Thanks for the suggestion! We will add the edit and delete functionality to the quacks in our next release! 🚀

**Comment by aicodingtu** [comment]
We added this feature when you open the paper, so users can make edit/delete  as they review the original content & surrounding context. 🚀 

![Screenshot 2023-07-30 at 22 15 10](https://github.com/aicodingtu/pond-alpha/assets/101179635/12fbc144-fd55-4002-9b75-62ecd52ea229)
